
spring: 
  output: 
    ansi:
      enabled: always
  messages:
    basename: /i18n/message
  profiles: 
    active: dev
  #MVC
  mvc:
    static-path-pattern: /**
    view:
      prefix: classpath:/templates/

#日志级别
logging: 
  config: classpath:log4j2.xml

swagger:
  enabled: true
  title: spring-boot-starter-swagger
  base-package: com.zfsoft
  base-path:
  - /**
  description: Starter for swagger 2.x
  exclude-path:
  - /error 
  - /ops/**
  version: 1.1.0.RELEASE
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  terms-of-service-url: https://github.com/dyc87112/spring-boot-starter-swagger
  contact:
    name :  正方软件股份有限公司
    email: zfsoft@zfsoft.com
    url  : http://www.zfsoft.com

fdfs:
  connect-timeout: 2000
  so-timeout: 3000
  tracker-list:
    - 10.1.5.85:22122
    - 10.1.5.86:22122