#日志级别
logging: 
  config: classpath:log4j2.xml

###############################################################################################################  
###Spring Boot 相关组件（SpringMVC、Freemarker、Session、Cache、DataSource）配置：  
################################################################################################################
spring: 
  messages:
    #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages
    basename: i18n/messages
    #设定Message bundles的编码，默认: UTF-8
    encoding: UTF-8
    
  profiles:
    active: dev
  
  #MVC
  mvc:
    static-path-pattern: /**
    view:
      prefix: classpath:/templates/
  resources:
    static-locations:
    - classpath:/templates/
  
  #freemarker视图配置
  freemarker:
    #是否允许mvc使用freemarker.
    enabled: true
    #设定Template的编码.
    charset: UTF-8
    #是否开启template caching.
    cache: false
    #设定Content-Type.
    content-type: text/html; charset=utf-8
    #指定HttpServletRequest的属性是否可以覆盖controller的model的同名项
    allow-request-override: false
    #指定HttpSession的属性是否可以覆盖controller的model的同名项
    allow-session-override: false
    #设定所有request的属性在merge到模板的时候，是否要都添加到model中.
    expose-request-attributes: false
    #设定所有HttpSession的属性在merge到模板的时候，是否要都添加到model中.
    expose-session-attributes: true
    #设定是否以springMacroRequestContext的形式暴露RequestContext给Spring’s macro library使用
    expose-spring-macro-helpers: true
    #是否优先从文件系统加载template，以支持热加载，默认为true; 设置为false时才可从其他jar包中加载指定模板路径下的模板文件
    prefer-file-system-access: false
    #指定RequestContext属性的名.
    request-context-attribute: request
    #是否检查templates路径是否存在.
    check-template-location: true
    #设定模板的加载路径，多个以逗号分隔，默认: ["classpath:/templates/"]
    template-loader-path: 
    - classpath:/templates
    #设定freemarker模板的前缀.
    #prefix: 
    #设定模板的后缀.
    suffix: .ftl
    settings:
      defaultEncoding : UTF-8
      url_escaping_charset: UTF-8
      locale: zh_CN
      template_update_delay: 1
      tag_syntax: auto_detect
      whitespace_stripping: true
      classic_compatible: true
      object_wrapper: freemarker.ext.beans.BeansWrapper
      templateExceptionHandler : ignore

socketio:
  server:
    hostname: localhost
    enabled: true
    port: 9098
    socket-config:
      reuse-address: true
      tcp-no-delay: true
      so-linger: 0