server:
  port: 8080

spring: 
  output:
    ansi:
      enabled: always
  messages:
    basename: /i18n/message
  profiles: 
    active: dev
    
zftal:
  http: 
    safety: 
      enabled: true
      url-patterns: /*
      definition-map:
        / : httpHeaderControl,httpMethodControl
        /webjars/** : noneControl
        /assets/** : noneControl
        /druid/** : noneControl
        /** : httpHeaderControl,httpMethodControl
      http-cors-filter:
        enabled: true
        access-control-allow-origin: '*'
        access-control-allow-credentials: true
        access-control-allow-headers: X-Requested-With
        access-control-allow-methods: GET,POST
      http-header-filter:
        enabled: true
        x-content-type-options: SAMEORIGIN
        x-frame-options: nosniff
        x-xss-protection: 1; mode=block
      http-methods-filter:
        enabled: true
        allowed-http-methods:
        - GET
        - POST
      http-richtext-xss-filter:
        enabled: true
        default-policy: classpath:conf/security/zfsoft-antixss-policy.xml
      http-xss-filter:
        enabled: false
#日志级别
logging: 
  config: classpath:log4j2.xml
    