
server:
  port: 8080

spring: 
  output:
    ansi:
      enabled: always
  messages:
    basename: /i18n/message
  profiles: 
    active: dev
    
################################################################################################################  
###Disruptor (DisruptorProperties) 基本配置：  
################################################################################################################       
disruptor: 
  enabled: true
  multi-producer: false
  ring-buffer-size: 1024
  ring-thread-numbers:  4
  #handler-definitions:
  #- /Event-DC-Output/TagA-Output/** = inDbPostHandler
  #- /Event-DC-Output/TagB-Output/** = smsPostHandler 
  
#日志级别
logging: 
  config: classpath:log4j2.xml
    