# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod

server:
  port: 8085

info:
  app:
    name: "@project.name@" #从pom.xml中获取
    description: "@project.description@"
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@"

spring: 
  output:
    ansi:
      enabled: always
  messages:
    basename: /i18n/message
  profiles: 
    active: dev
    
################################################################################################################  
###Rocketmq 客户端基本配置：  
################################################################################################################
rocketmq: 
  producer: 
    enabled: true
    producer-group: rmq-group-demo
    instance-name: rmq-instance
    namesrv-addr: 10.71.19.153:9876
  # ConsumeType.CONSUME_PASSIVELY : "PUSH" 模式
  consume-passively:
    enabled: true
    consumer-group: rmq-group-demo
    instance-name: rmq-instance
    namesrv-addr: 10.71.19.153:9876
   # subscription:
      #topic名称  : 根据实际情况设置消息的tag
      #数据中心数据上行主题  : 各个系统的标记
      #Topic-DSB : TagA-Input || TagB-Input || TagC-Input || TagD-Input || Notice-Input
#   event:
#     definition-map:
#       /Topic-DC-Input/TagA-Input/** : inDbHandler
#       /Topic-DC-Input/TagB-Input/** : smsHandler
#       /Topic-DC-Input/Notice-Input/** : noticeHandler
       
#日志级别
logging: 
  config: classpath:log4j2.xml
    