COMMENT ON COLUMN "ZFTAL_API_APPLY"."API_KEY" IS '接口KEY';
COMMENT ON COLUMN "ZFTAL_API_APPLY"."API_SECRET" IS '接口SECRET';
COMMENT ON COLUMN "ZFTAL_API_APPLY"."INVOKE_IP" IS '调用服务IP';
COMMENT ON COLUMN "ZFTAL_API_APPLY"."INVOKE_FREQUENCY" IS '接口调用频率';
COMMENT ON COLUMN "ZFTAL_API_APPLY"."APPLY_FILE" IS '申请文件';

-- ----------------------------
-- Table structure for ZFTAL_API_APPLY_CHANGE
-- ----------------------------
CREATE TABLE "ZFTAL_API_APPLY_CHANGE" (
"APPLY_CHANGE_ID" VARCHAR2(32 BYTE) DEFAULT sys_guid()  NOT NULL ,
"APPLY_ID" VARCHAR2(32 BYTE) NULL ,
"CHANGE_USER" VARCHAR2(32 BYTE) NULL ,
"CHANGE_TIME" VARCHAR2(30 BYTE) DEFAULT to_char(sysdate,'yyyy-mm-dd hh24:mi:ss')  NULL ,
"CHANGE_CONTENT" VARCHAR2(1024 BYTE) NULL ,
"CHANGE_FILE" BLOB NULL ,
"AUDIT_STATUS" VARCHAR2(2 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "ZFTAL_API_APPLY_CHANGE" IS '接口申请变更历史';
COMMENT ON COLUMN "ZFTAL_API_APPLY_CHANGE"."APPLY_CHANGE_ID" IS '变更历史ID';
COMMENT ON COLUMN "ZFTAL_API_APPLY_CHANGE"."APPLY_ID" IS '申请ID';
COMMENT ON COLUMN "ZFTAL_API_APPLY_CHANGE"."CHANGE_USER" IS '变更申请人';
COMMENT ON COLUMN "ZFTAL_API_APPLY_CHANGE"."CHANGE_TIME" IS '变更时间';
COMMENT ON COLUMN "ZFTAL_API_APPLY_CHANGE"."CHANGE_CONTENT" IS '变更内容';
COMMENT ON COLUMN "ZFTAL_API_APPLY_CHANGE"."CHANGE_FILE" IS '变更申请文件';
COMMENT ON COLUMN "ZFTAL_API_APPLY_CHANGE"."AUDIT_STATUS" IS '审核状态：0:待审核、1：审核通过、2：审核不通过';

-- ----------------------------
-- Indexes structure for table ZFTAL_API_APPLY_CHANGE
-- ----------------------------

-- ----------------------------
-- Checks structure for table ZFTAL_API_APPLY_CHANGE
-- ----------------------------
ALTER TABLE "ZFTAL_API_APPLY_CHANGE" ADD CHECK ("APPLY_CHANGE_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table ZFTAL_API_APPLY_CHANGE
-- ----------------------------
ALTER TABLE "ZFTAL_API_APPLY_CHANGE" ADD PRIMARY KEY ("APPLY_CHANGE_ID");