-- ----------------------------
-- Table structure for ZFTAL_API_INVOKE
-- ----------------------------
CREATE TABLE "ZFTAL_API_INVOKE" (
"API_ID" VARCHAR2(32 BYTE) NULL ,
"INVOKE_DEPLOY_ID" VARCHAR2(32 BYTE) NULL ,
"PARAM_RELATION" CLOB NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON TABLE "ZFTAL_API_INVOKE" IS '接口连续调用信息表';
COMMENT ON COLUMN "ZFTAL_API_INVOKE"."API_ID" IS '接口ID';
COMMENT ON COLUMN "ZFTAL_API_INVOKE"."INVOKE_DEPLOY_ID" IS '被调用的接口发布ID';
COMMENT ON COLUMN "ZFTAL_API_INVOKE"."PARAM_RELATION" IS '参数对应关系';