ALTER TABLE ZFTAL_API_APPLY ADD(
	API_KEY NVARCHAR2(256) DEFAULT NULL,
	API_SECRET NVARCHAR2(1024) DEFAULT NULL,
	INVOKE_IP NVARCHAR2(512) DEFAULT NULL,
	INVOKE_FREQUENCY NUMBER,
	APPLY_FILE BLOB DEFAULT NULL
);